### ISSUE TITLE
Make allowed TLS versions configurable

### ISSUE THREAD

**Issue by 4z3** [ip1981/sproxy2#14]
Sproxy2 currently is using warp-tls's `defaultTlsSettings`, which (up until at least [warp-tls 3.2.4.3](http://hackage.haskell.org/package/warp-tls-3.2.4.3)) specifies `tlsAllowedVersions` to be `[TLS12,TLS11,TLS10]`. As TLS 1.0 has reached its end of life, it might be desirable to remove that from the list (and while at it, maybe also TLS 1.1).

This could be accomplished in multiple ways. One of the arguably simplest ways would be to patch wrap-tls's `defaultTlsSettings` to just contain the desired versions. But as restricting the versions might be useful to other sproxy2 users, too, I've opened this issue to discuss the possibility of making `tlsAllowedVersions` configurable via sproxy2's config file. If it turns out that such a configuration option should be added to sproxy2, I can create a PR.

**Comment by ip1981** [comment]
I'd keep it simple and don't go into TLS stuff too deep, because it is not main job for Sproxy and it can work without TLS at all. Then, if TLS versions, why not the ciphers, etc.? :)

So if there is anything to be done, it is simple denying some TLS versions in the code. But what the point? As far as I understand both the client and the server should agree on the protocol, and if the client refuses or does not support TLS 1.0, we are good. And if we don't do anything (which is good), we will eventually get reasonable default settings from `warp-tls` when _they_ remove TLS1.0+ :)
